WIP: #210 bug fix for blochsteady
StollLab/EasySpin pull request #211
Opened 2021-03-17 16:07 UTC by sikuenstner

The bug fix for blochsteady uses the correct number of points as calculated from the maximum Fourier order if it is not specified in Options.nPoints to avoid "bandwidth" problems of the resulting time traces.
The Fourier order is now calculated such that the higher number of the two calculations of the Fourier order is used instead of the lower one.

2021-03-17 19:36 UTC, stestoll commented
Thanks for working on this!

Since this is labelled as WIP, I marked it as draft. When this PR is ready to review&merge, please remove WIP from the title and mark as "ready for review".

2021-03-23 10:39 UTC, sikuenstner commented
I see one problem with the combination of `blochsteady` and `rapidscan2spc`.

The no. of points automatically calculated from the Fourier order will always be odd. The function `rapidscan2spc`, however, needs an input with an even number of points, so that the two half cycles have the same length. 
For a simple usage of `blochsteady` and `rapidscan2spc` together as suggested in the user guide, I think this problem has to be resolved before submission. Below are three possible ways to handle the issue.

1. It could be mentioned in the description that in order to be used together, you need to specify an even number of points for blochsteady. This, however makes the whole change of `blochsteady` seem quite pointless, since my plan was to automatically calculate the no. of points in the first place.
2. Adding the last point standardly. Currently, in `blochsteady` only for plotting the last point is added, in order to have one complete cycle from t=0 to tLast=1/ModFreq with values of the magnetisation M(0) = M(tLast). Otherwise, the last point is omitted in order to be able to concatenate multiple time traces, I guess. Changing the standard output, however, may break current scripts. Additionally, `rapidscan2spc` needs to be adapted such that the time axis is calculated from 0 to tLast = 1/ModFreq. Adding a field to the Option structure like addLastPoint or removeLastPoint may be a solution to keep backwards compatibility.
3. Interpolate nPoints with an even number of points like nPoints +1.

Personally, I prefer option 2.

2021-03-23 17:18 UTC, stestoll commented
I agree this friction between the two function should be resolved. Can you post a minimal script example for the combined use of `blochsteady` and `rapidscan2spc`?

2021-04-23 11:40 UTC, sikuenstner commented
For option 2 `rapidscan2spc` needs to be changed to calculate the correct time axis as mentioned

1. Option 2 with backwards-compatibility of `blochsteady` by "manually" adding the last point:
```
g = 2;
ModAmp = 10;
ModFreq = 100;
Opt.AddLastPoint = 1; % last point is added, ensures an even number of points

[t,Mx,My,~] = blochsteady(g,0.11,0.1,0,0.1,ModAmp,ModFreq,Opt); % numel(t) = even

[B,spc] = rapidscan2spc(My+1i*Mx,ModAmp,ModFreq,g);
```

2. Option 2 with automatic adding of the last point breaking backwards-compatibility of `blochsteady`:
```
g = 2;
ModAmp = 10;
ModFreq = 100;

[t,Mx,My,~] = blochsteady(g,0.11,0.1,0,0.1,ModAmp,ModFreq); % numel(t) = even

[B,spc] = rapidscan2spc(My+1i*Mx,ModAmp,ModFreq,g);
```
To obtain old behaviour a field to Options could be passed: `Opt.RemoveLastPoint`.

```
g = 2;
ModAmp = 10;
ModFreq = 100;
Opt.RemoveLastPoint = 1;

[t,Mx,My,~] = blochsteady(g,0.11,0.1,0,0.1,ModAmp,ModFreq,Opt); % numel(t) = odd
```

2021-04-23 17:51 UTC, stestoll commented
Adding one more point in `blochsteady` at t=tmod to close the interval to yield [0,tmod] is not what `rapidscan2spc` needs.

For a clean solution of this issue, I think `blochsteady` must return an even number of points over the half-open interval [0,tmod) to be compatible with `rapidscan2spc`. There are two ways to achieve this: (a) adjust the k range used for setting up the linear problem, (b) keep the linear problem as is, and then use Fourier interpolation to increase the number of points by one. To me, (a) looks preferable.

2021-05-20 23:30 UTC, stestoll commented
@sikuenstner, what are your thoughts on this?

2021-05-25 12:49 UTC, sikuenstner commented
Sorry for my long absence. I think (a) is indeed preferable. Currently, the number of points is calculated from 2*kmax-1, which always returns an odd number. Is it enough to increment kmax when removing the -1?

2022-08-15 17:57 UTC, stestoll requested changes
The issue with the number of points doesn't seem to be resolved yet.

2022-08-15 17:57 UTC, stestoll commented
@sikuenstner , what remains to be done to finish this PR?

2022-10-12 07:18 UTC, stestoll commented
Closing PR

2022-10-12 07:18 UTC, closed without merging